name: Build Module

on:
  push:
    branches: ['mini']
    tags:
    - '*'

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Upload Asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      repository-projects: write

    steps:          
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Id
        id: mId
        run: echo "id=$(grep "^id=" module.prop|cut -d'=' -f2)" >> $GITHUB_OUTPUT
        
      - name: Get Version
        id: mVersion
        run: echo "version=$(grep "^version=" module.prop|cut -d'=' -f2)" >> $GITHUB_OUTPUT

      - name: Build project # This would actually build your project, using zip for an example artifact
        run: zip -r "${{ steps.mId.outputs.id }}.${{ steps.mVersion.outputs.version }}.zip" . -x "README.md" ".git/*" ".github/*" 

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ steps.mId.outputs.id }}.${{ steps.mVersion.outputs.version }}.zip"
          tag: ${{ steps.mVersion.outputs.version }}
