name: Build Module

on:
  push:
    tags: ['*']
    branches: ['master']

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Upload Asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      repository-projects: write

    steps:          
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Id
        id: mId
        run: echo "::set-output name=id::$(grep "^id=" module.prop|cut -d'=' -f2)"
        
      - name: Get Version
        id: mVersion
        run: echo "::set-output name=version::$(grep "^version=" module.prop|cut -d'=' -f2)"

      - name: Build project # This would actually build your project, using zip for an example artifact
        run: zip -r "${{ steps.mId.outputs.id }}.${{ steps.mVersion.outputs.version }}.zip" . -x "README.md" ".git/*" ".github/*" 

      - uses: ncipollo/release-action@v1
      - name: Upload Release
        with:
          artifacts: "${{ steps.mId.outputs.id }}.${{ steps.mVersion.outputs.version }}.zip"
          tag: ${{ steps.mVersion.outputs.version }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
